### ISSUE TITLE
syntax error easily fixable but i'm still having trouble generating QRcodes

### ISSUE THREAD

**Issue by josephedwardchang** [arup-group/QRCodeGenerator#13]
src\code\shared\qrcode_gen.py

line 9: bi.paste(qr, (5, 5, (width + 5), (height + 5))

missing final ')' close parenthesis.  This is easily fixable so I put the ')' at the end but now this error below shows up:

```
JEC:~/QRCodeGenerator/src$ cat /home/lad/QRCodeGen.csv
asset_name,asset_guid,size
DDC-1,2790e7ba-fe50-42df-a88e-87e0df6af11c,10
DDC-6,4d188085-77e2-4b99-ac54-e786267e9276,10
DDC-8,bb8e3719-320d-4ae0-bfa9-49300ba284d8,10
JEC:~/QRCodeGenerator/src$ sudo python3 run_qrcgeneration.py -t csv -f /home/lad/QRCodeGen.csv -o /home/lad/out -b False
Program arguments:
Namespace(bdnsflag='False', credsfile=False, filename='/home/lad/QRCodeGen.csv', gsheetid=False, inputtype='csv', output='/home/lad/out', verbose=True, worksheet='Sheet1')

Traceback (most recent call last):
  File "run_qrcgeneration.py", line 100, in <module>
    main()
  File "run_qrcgeneration.py", line 96, in main
    inputfile.start()
  File "/home/lad/QRCodeGenerator/src/code/inputType/csv/input2qrcode.py", line 69, in start
    bdns_abb = bdns_csv[['abbreviation', 'ifc_class']]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['abbreviation'] not in index"
```

which got me stumped. the error seems to be validation for bdns (which is supposed to be turned off) and even if it is turned on, it should pass bdns validation since my csv is using 'DDC' which is in bdns list. Can anyone point out what I am missing? Thanks for any info.

**Comment by a-o-u** [comment]
@ed

> 

It's trying to find the 'abbreviation' column in the [BDNS abbreviation register csv file](https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv) which has since changed from 'abbreviation' to 'asset_abbreviation'.

I've fixed the issue in my [fork](https://github.com/a-o-u/QRCodeGenerator). Hopefully It'll get merged soon.

**Comment by josephedwardchang** [comment]
awesome. thanks sir.

**Comment by josephedwardchang** [comment]
a-o-u's fork is working. Thanks.
